USE CPDB
GO

DROP PROCEDURE IF EXISTS pAddUser
DROP PROCEDURE IF EXISTS pUpdateUser
DROP PROCEDURE IF EXISTS pDeleteUser

DROP PROCEDURE IF EXISTS pAddRole
DROP PROCEDURE IF EXISTS pUpdateRole
DROP PROCEDURE IF EXISTS pDeleteRole

DROP PROCEDURE IF EXISTS pAddWorkCategory
DROP PROCEDURE IF EXISTS pUpdateWorkCategory
DROP PROCEDURE IF EXISTS pDeleteWorkCategory

DROP PROCEDURE IF EXISTS pAddEmployer
DROP PROCEDURE IF EXISTS pUpdateEmployer
DROP PROCEDURE IF EXISTS pDeleteEmployer
