USE CPDB
GO

DROP PROCEDURE IF EXISTS pAddUser
DROP PROCEDURE IF EXISTS pUpdateUser
DROP PROCEDURE IF EXISTS pDeleteUser

DROP PROCEDURE IF EXISTS pAddRole
DROP PROCEDURE IF EXISTS pUpdateRole
DROP PROCEDURE IF EXISTS pDeleteRole

DROP PROCEDURE IF EXISTS pAddWorkCategory
DROP PROCEDURE IF EXISTS pUpdateWorkCategory
DROP PROCEDURE IF EXISTS pDeleteWorkCategory

DROP PROCEDURE IF EXISTS pAddEmployer
DROP PROCEDURE IF EXISTS pUpdateEmployer
DROP PROCEDURE IF EXISTS pDeleteEmployer

DROP PROCEDURE IF EXISTS pAddVacancy
DROP PROCEDURE IF EXISTS pUpdateVacancy
DROP PROCEDURE IF EXISTS pDeleteVacancy

DROP PROCEDURE IF EXISTS pAddJobSeeker
DROP PROCEDURE IF EXISTS pUpdateJobSeeker
DROP PROCEDURE IF EXISTS pDeleteJobSeeker
