USE CPDB
GO

DROP TABLE IF EXISTS Deals
DROP TABLE IF EXISTS Vacancies
DROP TABLE IF EXISTS JobSeekers
DROP TABLE IF EXISTS Employers
DROP TABLE IF EXISTS WorkCategories
DROP TABLE IF EXISTS Users
DROP TABLE IF EXISTS Roles
